spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_management_system
    username: root
    password: "#Akosijomer02"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
logging:
  level:
    org.springframework: info